In [1]:
# 我弄了一个ppi文件进来，下面是展示这个ppi文件的demo

In [1]:
import pandas as pd
from scipy.sparse import coo_matrix
import networkx as nx
import scipy.sparse as sp
import numpy as np

In [2]:
ppi_network = pd.read_csv('data/networks/CPDB_symbols_edgelist.tsv', sep='\t')

In [3]:
ppi_network

        Unnamed: 0 partner1  partner2  confidence
0                2    STIM1     TRPC1    0.597177
1                3   ATP2B4      NOS1    0.520836
2                4    ABCC9    KCNJ11    0.990732
3                5    HADHB     HADHA    0.999980
4                6   GTF2E1    GTF2E2    0.973170
...            ...      ...       ...         ...
344857      521144   CAMKK2     CALM3    0.662630
344858      521146      FGA     ITGB1    0.994544
344859      521147    CREB1     GTF2B    0.998347
344860      521148     MTOR  EIF4EBP3    0.801299
344861      521149      F2R      DVL1    0.941436

[344862 rows x 4 columns]

In [5]:
## 这个就是ppi矩阵
ppi_network.head()

,STIM1,TRPC1,ATP2B4,NOS1,ABCC9,KCNJ11,HADHB,HADHA,GTF2E1,GTF2E2,...,GPC2,LAIR1,CRIM1,ADGRG6,NPPC,SIRPB2,GPR153,HDC,CSMD1,PPP1R1A
STIM1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TRPC1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATP2B4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NOS1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ABCC9,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
## gene的名字，后续需要对齐
ppi_network.columns

Index(['STIM1', 'TRPC1', 'ATP2B4', 'NOS1', 'ABCC9', 'KCNJ11', 'HADHB', 'HADHA',
       'GTF2E1', 'GTF2E2',
       ...
       'GPC2', 'LAIR1', 'CRIM1', 'ADGRG6', 'NPPC', 'SIRPB2', 'GPR153', 'HDC',
       'CSMD1', 'PPP1R1A'],
      dtype='object', length=14092)

In [4]:
ppi_graph = nx.from_pandas_edgelist(df=ppi_network, source='partner1', target='partner2', edge_attr='confidence')
ppi_network = nx.to_pandas_adjacency(G=ppi_graph)
##get edge
coo_ppi_network = coo_matrix(ppi_network)
edge_index = [coo_ppi_network.row, coo_ppi_network.col]
print('ppi_network have ',len(ppi_network.index), 'genes')

ppi_network have  14092 genes

In [13]:
data = np.ones(edge_index[1].shape[0])
adj = sp.coo_matrix((data, (edge_index[0], edge_index[1])), shape=(ppi_network.shape[0], ppi_network.shape[1]), dtype=np.float32)

In [8]:
ppi_network.to_csv('/root/work/data/ppi_network', index=1)